export const ProjectList = [
  {
    id: 1,
    title: "National Research Institute Platform",
    description:
      "A large-scale enterprise system for a national research body. Developed complex CRUD modules, multi-layered data relationships, and a robust 'Save Draft' system to ensure data integrity for researchers.",
    img: "/logo-hsai.svg",
    images: ["/logo-hsai.svg", "/logo-hsai.svg"],
    date: "Dec 2025 - Feb 2026",
    category: "Full-Stack (Professional)",
    technologies: [
      "React",
      "TypeScript",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Tailwind CSS",
      "Prisma",
      "AI-Assisted Tools",
    ],
    githubUrl: "",
  },
  {
    id: 2,
    title: "Online Restaurant Platform",
    description:
      "A restaurant booking system with reservations, booking history, restaurant management, and notifications.",
    img: "/res_1.png",
    images: [
      "/res_1.png",
      "/res_2.png",
      "/res_3.png",
      "/res_4.png",
      "/res_5.png",
    ],
    date: "Nov 2024 - Feb 2025",
    category: "Full-Stack (Capstone Project)",
    technologies: [
      "HTML",
      "React",
      "Node.js",
      "Axios",
      "Express.js",
      "Tailwind CSS",
      "MySQL",
      "Socket.io",
      "vite.js",
    ],
    githubUrl: "https://github.com/Siraphop-x/-Final_project",
  },
  {
    id: 3,
    title: "CRUD, Login, and Registration System",
    description:
      "A small CRUD project to experiment with basic fullstack PHP web development and database connection.",
    img: "/php-1.png",
    images: ["/php-1.png", "/php-2.png", "/php-3.png", "/php-4.png"],
    date: "Dec 2024",
    category: "Full-Stack (Mini Project)",
    technologies: ["HTML", "PHP", "Bootstrap 5", "MySQL"],
    githubUrl: "https://github.com/Siraphop-x",
  },
  {
    id: 4,
    title: "Web portfolio",
    description:
      "Portfolio website developed with React and Tailwind CSS, showcasing professional experience and modern web development skills with interactive animations.",
    img: "/img_port.png",
    images: ["/img_port.png", "/image_port.2.png", "/image_port.3.png"],
    date: "May 2025",
    category: "Front-End",
    technologies: [
      "React",
      "Tailwind CSS",
      "daisyUI",
      "vite.js",
      "Lucide React",
    ],
    githubUrl: "https://github.com/Siraphop-x",
  },
  {
    id: 5,
    title: "Employee Management System",
    description:
      "A small React fullstack project for managing employee data with seamless database integration.",
    img: "/emp-1.png",
    images: ["/emp-1.png", "/emp-2.png"],
    date: "March 2024",
    category: "Full-Stack (Mini Project)",
    technologies: ["React", "Tailwind CSS", "node.js", "express.js", "MySQL"],
    githubUrl: "",
  },
  {
    id: 6,
    title: "Front-End Developer (Internship)",
    description:
      "Contributed to a government 'Payment System' focusing on high-quality UI components and state management for large-scale enterprise data.",
    img: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=400&h=250&fit=crop",
    date: "Nov 2024 - Feb 2025",
    category: "(Front-End) Internship",
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Redux",
      "Tailwind CSS",
      "antd",
    ],
    githubUrl: "",
  },
  {
    id: 7,
    title: "Galaxy Blaster",
    description:
      "A cutting-edge space shooter game combining Phaser 3 for 2D gameplay with Three.js for immersive 3D galaxy backgrounds. Features TypeScript architecture, real-time physics, and dynamic visual effects.",
    img: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&h=250&fit=crop",
    images: ["https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&h=250&fit=crop"],
    date: "Mar 2026",
    category: "Game Development",
    technologies: [
      "TypeScript",
      "Phaser 3",
      "Three.js",
      "Vite",
      "Tailwind CSS",
      "HTML5 Canvas",
      "WebGL",
      "Game Physics",
    ],
    githubUrl: "https://github.com/Siraphop-x/galaxy-blaster",
    liveDemo: "https://galaxy-blaster-smoky.vercel.app/",
  },
];
